<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-DT4EAKM" name="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest" tests="7" failures="0" timestamp="2020-05-12T22:36:19 COT" time="0.040" errors="2">
  <testcase name="testUpdateTopic2" time="0.014" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest"/>
  <system-out/>
  <testcase name="testAddTopic1" time="0.006" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at co.edu.icesi.internetcomputing.workshop.services.TsscTopicServiceImp.save(TsscTopicServiceImp.java:33)
at co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest.testAddTopic1(TsscTopicServiceTest.java:47)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testAddTopic1 -->
  <system-out/>
  <testcase name="testAddTopic3" time="0.003" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest"/>
  <system-out/>
  <testcase name="testAddTopicNull" time="0.006" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest"/>
  <system-out/>
  <testcase name="testUpdateTopic3" time="0.005" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest"/>
  <system-out/>
  <testcase name="testUpdateTopic1" time="0.003" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at co.edu.icesi.internetcomputing.workshop.services.TsscTopicServiceImp.save(TsscTopicServiceImp.java:33)
at co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest.testUpdateTopic1(TsscTopicServiceTest.java:123)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testUpdateTopic1 -->
  <system-out/>
  <testcase name="testAddTopic2" time="0.003" classname="co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest"/>
  <system-out/>
</testsuite> <!-- co.edu.icesi.internetcomputing.workshop.unit_tests.TsscTopicServiceTest -->
